### ISSUE TITLE
rewireFromRoot should be outside if

### ISSUE THREAD

**Issue by jpoikela** [ptsneves/rt-rrt#2]
I think this should be outside the if 
https://github.com/ptsneves/rt-rrt/blob/master/rt.py#L301

according to the research paper and a similar line in java implementation:
https://github.com/Peng154/real-time-path-planning-for-Simbad/blob/2bffe54fcd80583266b679dfb127fff1c1da86a6/src/com/rt_rrt/RTRRTStar.java#L174

**Comment by ptsneves** [comment]
@jpoikela thanks for the review. You are right. I have not finished the implementation yet, but your comments gave me some incentive to try to finish it.
I will push the changes after I do more adjustments.
Would you be interested in trying this code out in a small rc with ultra sound sensors?

**Comment by jpoikela** [comment]
It would be nice to see the code completed, it's a good start! I've spent some hours with it and the java implementation for Simbad. but I like Python more :smile: your seems to be only one available in github.. some rrt and other derived implementations exist, though.

I don't know how I could try it out, how would I get such rc car? But yes, I'm interested in trying it out somehow..

**Comment by ptsneves** [comment]
I fixed error and added a README.
If you run it it should produce an SVG. The README has a small explanation on the color code and content of the svg.

In the next few days I will try to clean the code to make it easier for other to understand, while keeping it very concise.

I think any crappy RC car, I will elaborate on this soon as this was the goal of exploring this algorithm. By the way, what are your motivations for studying this algorithm?

**Comment by jpoikela** [comment]
I was wondering it I could use it for controlling Lego Mindstorm car.. I guess the lego set does not have enough processing power, but having computer do it should not be too difficult.
this is just a hobby project, but understanding these algorithms would be nice too 🙂
